
CREATE TABLE STUDENT (STUD_ID NUMBER NOT NULL 
, FIRSTNAME VARCHAR2(20) 
, LASTNAME VARCHAR2(20) 
, USERNAME VARCHAR2(20) 
, S_PASSWORD VARCHAR2(20) 
, CITY VARCHAR2(20) 
, EMAIL VARCHAR2(20) 
, MOBILENUMBER VARCHAR2(20) 
, CONSTRAINT STUDENT_PK PRIMARY KEY (STUD_ID));

CREATE SEQUENCE STUDID_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM student;

ALTER TABLE STUDENT MODIFY EMAIL VARCHAR2(50);

SELECT USERNAME, S_PASSWORD FROM STUDENT WHERE UserName = 'om_surve' AND s_password = '12345';

------------------------------------------------------------------------------------------------